// MESSAGE
export const SET_MESSAGE = 'SET_MESSAGE';

// PLAYER
export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE';
export const UPDATE_PLAYER_INFO = 'UPDATE_PLAYER_INFO';

// RADIO
export const REGISTER_RADIO_BEGIN = 'REGISTER_RADIO_BEGIN';
export const REGISTER_RADIO_SUCCESS = 'REGISTER_RADIO_SUCCESS';
export const REGISTER_RADIO_FAILURE = 'REGISTER_RADIO_FAILURE';

export const SEARCH_RADIO_BEGIN = 'SEARCH_RADIO_BEGIN';
export const SEARCH_RADIO_SUCCESS = 'SEARCH_RADIO_SUCCESS';
export const SEARCH_RADIO_FAILURE = 'SEARCH_RADIO_FAILURE';

// USER
export const AUTH_USER_BEGIN = 'AUTH_USER_BEGIN';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
export const USERS_LOGOUT = 'USERS_LOGOUT';