export const RADIO_UPDATE_STATE = 'RADIO_UPDATE_STATE';
export const RADIO_UPDATE_INFO = 'RADIO_UPDATE_INFO';
export const SET_MESSAGE = 'SET_MESSAGE';
export const RADIO_REGISTERED = 'RADIO_REGISTERED';

export const userConstants = {
  AUTH_REQUEST: 'USERS_AUTH_REQUEST',
  AUTH_SUCCESS: 'USERS_AUTH_SUCCESS',
  AUTH_FAILURE: 'USERS_AUTH_FAILURE',
  LOGOUT: 'USERS_LOGOUT'
};