# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'

target 'radios99' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  target 'radios99Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'radios99-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for radios99-tvOS

  target 'radios99-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
